# 应用 ID，需修改成自己的应用 ID（在开发者中心获取）
id: ${packageId}

# 自定义安装参数，通过 widget 来声明安装表单获取
args:
  - name: app_target
    label: 目标网络
    widget: subnet-select
    supportedRegionIds:
      - 1
  - name: security_group
    label: 安全组
    widget: security-group-select
    regions:
      - ap-guangzhou
